app/thing/forms.py
from flask_wtf import FlaskForm
from wtforms import RadioField, SelectField, StringField
from wtforms.validators import InputRequired, Length, Optional


class ThingForm(FlaskForm):
    name = StringField(
        "Name",
        validators=[
            InputRequired(message="Enter a name"),
            Length(max=32, message="Name must be 32 characters or fewer"),
        ],
        description="Must be 32 characters or fewer.",
    )
    colour = RadioField(
        "Colour",
        validators=[InputRequired(message="Select a colour")],
        choices=[
            ("red", "Red"),
            ("green", "Green"),
            ("blue", "Blue"),
            ("yellow", "Yellow"),
            ("orange", "Orange"),
            ("purple", "Purple"),
            ("black", "Black"),
            ("white", "White"),
        ],
    )


class ThingFilterForm(FlaskForm):
    sort = SelectField(
        "Sort by",
        validators=[InputRequired()],
        choices=[("name", "Name"), ("colour", "Colour")],
        default="name",
    )
    name = StringField("Name", validators=[Optional()])
    colour = RadioField(
        "Colour",
        validators=[Optional()],
        choices=[
            ("red", "Red"),
            ("green", "Green"),
            ("blue", "Blue"),
            ("yellow", "Yellow"),
            ("orange", "Orange"),
            ("purple", "Purple"),
            ("black", "Black"),
            ("white", "White"),
        ],
        default="",
    )

app/thing/__init__.py
from flask import Blueprint

bp = Blueprint("thing", __name__, template_folder="../templates/thing")

from app.thing import routes  # noqa: E402,F401

app/thing/routes.py
from flask import Response, flash, redirect, render_template, request, url_for

from app import csrf
from app.integrations.thing_api import Thing
from app.thing import bp
from app.thing.forms import ThingFilterForm, ThingForm


@bp.route("/", methods=["GET", "POST"])
def list():
    """Get a list of Things."""
    form = ThingFilterForm()

    filters = {}
    if request.args.get("sort"):
        filters["sort"] = request.args.get("sort", type=str)
        form.sort.data = filters["sort"]
    if request.args.get("name"):
        filters["name"] = request.args.get("name", type=str)
        form.name.data = filters["name"]
    if request.args.get("colour"):
        filters["colour"] = request.args.get("colour", type=str)
        form.colour.data = filters["colour"]

    things = Thing().list(filters=filters)

    return render_template("list_things.html", title="Things", things=things, form=form)


@bp.route("/new", methods=["GET", "POST"])
def create():
    """Create a new Thing."""
    form = ThingForm()

    if form.validate_on_submit():
        new_thing = Thing().create(name=form.name.data, colour=form.colour.data)
        flash(
            "<a href='{}' class='alert-link'>{}</a> has been created.".format(
                url_for("thing.view", id=new_thing["id"]), new_thing["name"]
            ),
            "success",
        )
        return redirect(url_for("thing.list"))

    return render_template("create_thing.html", title="Create a new thing", form=form)


@bp.route("/<uuid:id>", methods=["GET"])
def view(id):
    """Get a Thing with a specific ID."""
    thing = Thing().get(id)

    return render_template("view_thing.html", title=thing["name"], thing=thing)


@bp.route("/<uuid:id>/edit", methods=["GET", "POST"])
def edit(id):
    """Edit a Thing with a specific ID."""
    thing = Thing().get(id)
    form = ThingForm()

    if form.validate_on_submit():
        changed_thing = Thing().edit(thing_id=id, name=form.name.data, colour=form.colour.data)
        flash(
            "Your changes to <a href='{}' class='alert-link'>{}</a> have been saved.".format(
                url_for("thing.view", id=changed_thing["id"]), changed_thing["name"]
            ),
            "success",
        )
        return redirect(url_for("thing.list"))
    elif request.method == "GET":
        form.name.data = thing["name"]
        form.colour.data = thing["colour"]

    return render_template(
        "update_thing.html",
        title=f"Edit {thing['name']}",
        form=form,
        thing=thing,
    )


@bp.route("/<uuid:id>/delete", methods=["GET", "POST"])
@csrf.exempt
def delete(id):
    """Delete a Thing with a specific ID."""
    thing = Thing().get(id)

    if request.method == "GET":
        return render_template(
            "delete_thing.html",
            title=f"Delete {thing['name']}",
            thing=thing,
        )
    elif request.method == "POST":
        Thing().delete(id)
        flash(f"{thing['name']} has been deleted.", "success")
        return redirect(url_for("thing.list"))


@bp.route("/download", methods=["GET"])
def download():
    """Download a list of Things."""
    filters = {}
    if request.args.get("sort"):
        filters["sort"] = request.args.get("sort", type=str)
    if request.args.get("name"):
        filters["name"] = request.args.get("name", type=str)
    if request.args.get("colour"):
        filters["colour"] = request.args.get("colour", type=str)

    things = Thing().list(filters=filters, format="csv")
    response = Response(things, mimetype="text/csv", status=200)
    response.headers.set("Content-Disposition", "attachment", filename="things.csv")
    return response

app/templates/thing/_thing_description.html
<dl class="row">
    <dt class="col-sm-3">Colour</dt>
    <dd class="col-sm-9">{{ thing.colour | title }}</dd>

    <dt class="col-sm-3">Created</dt>
    <dd class="col-sm-9">{{ thing.created_at.strftime("%d/%m/%Y %H:%M:%S") }}</dd>

    <dt class="col-sm-3">Last updated</dt>
    <dd class="col-sm-9">{{ thing.updated_at.strftime("%d/%m/%Y %H:%M:%S") if thing.updated_at else "Never" }}</dd>
</dl>

app/templates/thing/_thing_form.html
<form action="" method="post" novalidate>
    {{ form.csrf_token }}
    <div class="mb-3">
        {{ form.name.label(class="form-label") }}
        {% if form.errors %}
            {% if form.name.errors %}
                {{ form.name(class="form-control is-invalid", type="text", spellcheck="true", aria_describedby="nameHelp") }}
                {% for error in form.name.errors %}<div class="invalid-feedback">{{error}}</div>{% endfor %}
            {% else %}
                {{ form.name(class="form-control is-valid", type="text", spellcheck="true", aria_describedby="nameHelp") }}
                <div class="valid-feedback">Looks good!</div>
            {% endif %}
        {% else %}
            {{ form.name(class="form-control", type="text", spellcheck="true", aria_describedby="nameHelp") }}
        {% endif %}
        <div id="nameHelp" class="form-text">{{ form.name.description }}</div>
    </div>
    <div class="mb-3">
        {{ form.colour.label(class="form-label") }}
        {% if form.errors %}
            {% if form.colour.errors %}
                {% for subfield in form.colour %}
                <div class="form-check mb-3">
                    {{ subfield(class="form-check-input is-invalid", type="radio") }}
                    {{ subfield.label(class="form-check-label") }}
                    {% for error in form.colour.errors %}<div class="invalid-feedback">{{error}}</div>{% endfor %}
                </div>
                {% endfor %}
            {% else %}
                {% for subfield in form.colour %}
                <div class="form-check">
                    {{ subfield(class="form-check-input is-valid", type="radio") }}
                    {{ subfield.label(class="form-check-label") }}
                </div>
                {% endfor %}
            {% endif %}
        {% else %}
            {% for subfield in form.colour %}
            <div class="form-check">
                {{ subfield(class="form-check-input", type="radio") }}
                {{ subfield.label(class="form-check-label") }}
            </div>
            {% endfor %}
        {% endif %}
    </div>
    <div class="d-grid gap-3 d-sm-block">
        <button class="btn btn-primary" type="submit"><i class="bi bi-save"></i> Save</button>
    </div>
</form>

app/templates/thing/create_thing.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url_for('thing.list') }}">Things</a></li>
                <li class="breadcrumb-item active" aria-current="page">New</li>
            </ol>
        </nav>
        {{ super() }}
        <h1>{{title}}</h1>
        <hr>
        {% include '_thing_form.html' %}
    </div>
</div>
{% endblock %}

app/templates/thing/delete_thing.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url_for('thing.list') }}">Things</a></li>
                <li class="breadcrumb-item"><a href="{{ url_for('thing.view', id=thing.id) }}">{{ thing.name }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">Delete</li>
            </ol>
        </nav>
        {{ super() }}
        <h1>{{title}}</h1>
        <hr>
        <p class="lead">Are you sure you want to delete {{ thing.name }}?</p>
        {% include '_thing_description.html' %}
        <form action="" method="post" novalidate>
            <div class="d-grid gap-3 d-sm-block">
                <button class="btn btn-danger" type="submit"><i class="bi bi-trash"></i> Yes, delete {{ thing.name }}</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/thing/list_things.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col">
        {{ super() }}
        <h1>{{title}}</h1>
        <hr>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <div class="d-grid gap-3 mb-3">
            <a class="btn btn-primary btn-lg" href="{{ url_for('thing.create') }}"><i class="bi bi-plus-lg"></i> New thing</a>
        </div>
        <div class="card mb-3">
            <div class="card-header">Sort and filter</div>
            <form action="" method="get" novalidate>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        {{ form.sort.label(class="form-label") }}
                        {{ form.sort(class="form-select mb-2") }}
                    </li>
                    <li class="list-group-item">
                        {{ form.name.label(class="form-label") }}
                        {{ form.name(class="form-control mb-2", type="text") }}
                    </li>
                    <li class="list-group-item">
                        {{ form.colour.label(class="form-label") }}
                        {% for subfield in form.colour %}
                            <div class="form-check">
                                {{ subfield(class="form-check-input", type="radio") }}
                                {{ subfield.label(class="form-check-label") }}
                            </div>
                        {% endfor %}
                    </li>
                </ul>
                <div class="card-body">
                    <div class="d-grid gap-3">
                        <button class="btn btn-primary" type="submit"><i class="bi bi-funnel"></i> Apply</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-9">
        {% if things %}
        <p class="lead">
            {{ things|length }} {% if things|length == 1 %}thing{% else %}things{% endif %}
            <a class="btn btn-secondary float-end" href="{{ url_for('thing.download', sort=request.args.get('sort'), name=request.args.get('name'), colour=request.args.get('colour')) }}"><i class="bi bi-download"></i> Download</a>
        </p>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Colour</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for thing in things %}
                        <tr>
                            <th scope="row"><a href="{{ url_for('thing.view', id=thing.id) }}">{{ thing.name }}</a></th>
                            <td>{{ thing.colour | title }}</td>
                            <td>
                                <a href="{{ url_for('thing.edit', id=thing.id) }}"><i class="bi bi-pencil-square"></i> Edit</a><br>
                                <a href="{{ url_for('thing.delete', id=thing.id) }}" class="link-danger"><i class="bi bi-trash"></i> Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <p class="lead">0 things</p>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/thing/update_thing.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url_for('thing.list') }}">Things</a></li>
                <li class="breadcrumb-item"><a href="{{ url_for('thing.view', id=thing.id) }}">{{ thing.name }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">Edit</li>
            </ol>
        </nav>
        {{ super() }}
        <h1>{{title}}</h1>
        <hr>
        {% include '_thing_form.html' %}
    </div>
</div>
{% endblock %}

app/templates/thing/view_thing.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url_for('thing.list') }}">Things</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ title }}</li>
            </ol>
        </nav>
        {{ super() }}
        <h1 class="text-truncate">{{ title }}</h1>
        <hr>
        {% include '_thing_description.html' %}
        <div class="d-grid gap-3 d-sm-block">
            <a class="btn btn-primary" href="{{ url_for('thing.edit', id=thing.id) }}"><i class="bi bi-pencil-square"></i> Edit</a>
            <a class="btn btn-danger" href="{{ url_for('thing.delete', id=thing.id) }}"><i class="bi bi-trash"></i> Delete</a>
        </div>
    </div>
</div>
{% endblock %}