app/point/forms.py
from flask_wtf import FlaskForm
from wtforms import HiddenField, SelectField, StringField
from wtforms.validators import InputRequired, Length, Optional


class PointForm(FlaskForm):
    name = StringField(
        "Name",
        validators=[
            InputRequired(message="Enter a name"),
            Length(max=32, message="Name must be 32 characters or fewer"),
        ],
        description="Must be 32 characters or fewer.",
    )
    location = HiddenField(
        "Location",
        validators=[InputRequired(message="Select a location")],
        description="Click on the map to add a location.",
    )


class PointFilterForm(FlaskForm):
    sort = SelectField(
        "Sort by",
        validators=[InputRequired()],
        choices=[("name", "Name")],
        default="name",
    )
    name = StringField("Name", validators=[Optional()])

app/point/__init__.py
from flask import Blueprint

bp = Blueprint("point", __name__, template_folder="../templates/point")

from app.point import routes  # noqa: E402,F401

app/point/routes.py
import json

from flask import Response, flash, redirect, render_template, request, url_for

from app import csrf
from app.integrations.point_api import Point
from app.point import bp
from app.point.forms import PointFilterForm, PointForm


@bp.route("/", methods=["GET", "POST"])
def list():
    """Get a list of Points."""
    form = PointFilterForm()

    filters = {}
    if request.args.get("sort"):
        filters["sort"] = request.args.get("sort", type=str)
        form.sort.data = filters["sort"]
    if request.args.get("name"):
        filters["name"] = request.args.get("name", type=str)
        form.name.data = filters["name"]

    points = Point().list(filters=filters)

    return render_template("list_points.html", title="Points", points=points, form=form)


@bp.route("/new", methods=["GET", "POST"])
def create():
    """Create a new Point."""
    form = PointForm()

    if form.validate_on_submit():
        new_point = Point().create(name=form.name.data, geometry=form.location.data)
        flash(
            "<a href='{}' class='alert-link'>{}</a> has been created.".format(
                url_for("point.view", id=new_point["id"]),
                new_point["properties"]["name"],
            ),
            "success",
        )
        return redirect(url_for("point.list"))

    return render_template("create_point.html", title="Create a new point", form=form)


@bp.route("/<uuid:id>", methods=["GET"])
def view(id):
    """Get a Point with a specific ID."""
    point = Point().get(id)

    return render_template("view_point.html", title=point["properties"]["name"], point=point)


@bp.route("/<uuid:id>/edit", methods=["GET", "POST"])
def edit(id):
    """Edit a Point with a specific ID."""
    point = Point().get(id)
    form = PointForm()

    if form.validate_on_submit():
        changed_point = Point().edit(point_id=id, name=form.name.data, geometry=form.location.data)
        flash(
            "Your changes to <a href='{}' class='alert-link'>{}</a> have been saved.".format(
                url_for("point.view", id=changed_point["id"]),
                changed_point["properties"]["name"],
            ),
            "success",
        )
        return redirect(url_for("point.list"))
    elif request.method == "GET":
        form.name.data = point["properties"]["name"]
        form.location.data = json.dumps(point["geometry"])

    return render_template(
        "update_point.html",
        title=f"Edit {point['properties']['name']}",
        form=form,
        point=point,
    )


@bp.route("/<uuid:id>/delete", methods=["GET", "POST"])
@csrf.exempt
def delete(id):
    """Delete a Point with a specific ID."""
    point = Point().get(id)

    if request.method == "GET":
        return render_template(
            "delete_point.html",
            title=f"Delete {point['properties']['name']}",
            point=point,
        )
    elif request.method == "POST":
        Point().delete(id)
        flash(f"{point['properties']['name']} has been deleted.", "success")
        return redirect(url_for("point.list"))


@bp.route("/download", methods=["GET"])
def download():
    """Download a list of Points."""
    filters = {}
    if request.args.get("sort"):
        filters["sort"] = request.args.get("sort", type=str)
    if request.args.get("name"):
        filters["name"] = request.args.get("name", type=str)

    points = Point().list(filters=filters, format="csv")
    response = Response(points, mimetype="text/csv", status=200)
    response.headers.set("Content-Disposition", "attachment", filename="points.csv")
    return response

app/templates/point/_point_description.html
<dl class="row">
    <dt class="col-sm-3">Created</dt>
    <dd class="col-sm-9">{{ point.properties.created_at.strftime("%d/%m/%Y %H:%M:%S") }}</dd>

    <dt class="col-sm-3">Last updated</dt>
    <dd class="col-sm-9">{{ point.properties.updated_at.strftime("%d/%m/%Y %H:%M:%S") if point.properties.updated_at else "Never" }}</dd>
</dl>
<div id="mapid" class="card mb-3"></div>
<script type="application/javascript" nonce="{{ csp_nonce() }}">
    // initialize Leaflet
    var map = L.map("mapid");

    // add the OpenStreetMap tiles
    L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
    maxZoom: 19,
    attribution:
        '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>',
    }).addTo(map);

    // add popup to each feature
    function onEachFeature(feature, layer) {
        if (feature.properties && feature.properties.name) {
            layer.bindPopup(feature.properties.name);
        }
    }

    // add the GeoJSON feature layer
    var geojsonLayer = L.geoJSON({{ point | tojson }}, { onEachFeature: onEachFeature }).addTo(map);

    // zoom map to GeoJSON feature layer
    map.fitBounds(geojsonLayer.getBounds());
</script>
<input type="hidden" id="geometry">

app/templates/point/_point_form.html
<form action="" method="post" novalidate>
    {{ form.csrf_token }}
    <div class="mb-3">
        {{ form.name.label(class="form-label") }}
        {% if form.errors %}
            {% if form.name.errors %}
                {{ form.name(class="form-control is-invalid", type="text", spellcheck="true", aria_describedby="nameHelp") }}
                {% for error in form.name.errors %}<div class="invalid-feedback">{{error}}</div>{% endfor %}
            {% else %}
                {{ form.name(class="form-control is-valid", type="text", spellcheck="true", aria_describedby="nameHelp") }}
                <div class="valid-feedback">Looks good!</div>
            {% endif %}
        {% else %}
            {{ form.name(class="form-control", type="text", spellcheck="true", aria_describedby="nameHelp") }}
        {% endif %}
        <div id="nameHelp" class="form-text">{{ form.name.description }}</div>
    </div>
    <div class="mb-3">
        {{ form.location.label(class="form-label") }}
        {% if form.errors %}
            {% if form.location.errors %}
                <div id="mapid" class="card border-danger"></div>
                {{ form.location(class="is-invalid") }}
                {% for error in form.location.errors %}<div class="invalid-feedback">{{error}}</div>{% endfor %}
            {% else %}
                <div id="mapid" class="card border-success"></div>
                {{ form.location(class="is-valid") }}
                <div class="valid-feedback">Looks good!</div>
            {% endif %}
        {% else %}
            {{ form.location }}
            <div id="mapid" class="card"></div>
        {% endif %}
        <div id="nameHelp" class="form-text">{{ form.location.description }}</div>
    </div>
    <div class="d-grid gap-3 d-sm-block">
        <button class="btn btn-primary" type="submit"><i class="bi bi-save"></i> Save</button>
    </div>
</form>

app/templates/point/create_point.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url_for('point.list') }}">Points</a></li>
                <li class="breadcrumb-item active" aria-current="page">New</li>
            </ol>
        </nav>
        {{ super() }}
        <h1>{{title}}</h1>
        <hr>
        {% include '_point_form.html' %}
        <script type="application/javascript" nonce="{{ csp_nonce() }}">
            // initialize Leaflet
            var map = L.map("mapid");

            // add the OpenStreetMap tiles
            L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
                maxZoom: 19,
                attribution:
                    '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>',
            }).addTo(map);

            //set map view to users geolocation
            map.locate({ setView: true, maxZoom: 16 });

            var marker = L.marker();

            function onMapClick(e) {
                marker
                    .setLatLng(e.latlng)
                    .addTo(map)
                    .bindPopup(
                    "Lon: " + e.latlng.lng.toString() + "<br>Lat: " + e.latlng.lat.toString()
                    )
                    .openPopup();
                document.getElementById("location").value = JSON.stringify(
                    marker.toGeoJSON().geometry
                );
            }

            map.on("click", onMapClick);
        </script>
    </div>
</div>
{% endblock %}

app/templates/point/delete_point.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url_for('point.list') }}">Points</a></li>
                <li class="breadcrumb-item"><a href="{{ url_for('point.view', id=point.id) }}">{{ point.properties.name }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">Delete</li>
            </ol>
        </nav>
        {{ super() }}
        <h1>{{title}}</h1>
        <hr>
        <p class="lead">Are you sure you want to delete {{ point.properties.name }}?</p>
        {% include '_point_description.html' %}
        <form action="" method="post" novalidate>
            <div class="d-grid gap-3 d-sm-block">
                <button class="btn btn-danger" type="submit"><i class="bi bi-trash"></i> Yes, delete {{ point.properties.name }}</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/point/list_points.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col">
        {{ super() }}
        <h1>{{title}}</h1>
        <hr>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <div class="d-grid gap-3 mb-3">
            <a class="btn btn-primary btn-lg" href="{{ url_for('point.create') }}"><i class="bi bi-plus-lg"></i> New point</a>
        </div>
        <div class="card mb-3">
            <div class="card-header">Sort and filter</div>
            <form action="" method="get" novalidate>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        {{ form.sort.label(class="form-label") }}
                        {{ form.sort(class="form-select mb-2") }}
                    </li>
                    <li class="list-group-item">
                        {{ form.name.label(class="form-label") }}
                        {{ form.name(class="form-control mb-2", type="text") }}
                    </li>
                </ul>
                <div class="card-body">
                    <div class="d-grid gap-3">
                        <button class="btn btn-primary" type="submit"><i class="bi bi-funnel"></i> Apply</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-9">
        {% if points %}
        <p class="lead">
            {{ points.features|length }} {% if points.features|length == 1 %}point{% else %}points{% endif %}
            <a class="btn btn-secondary float-end" href="{{ url_for('point.download', sort=request.args.get('sort'), name=request.args.get('name')) }}"><i class="bi bi-download"></i> Download</a>
        </p>
        <div id="mapid" class="card"></div>
        <script type="application/javascript" nonce="{{ csp_nonce() }}">
            // initialize Leaflet
            var map = L.map("mapid");

            // add the OpenStreetMap tiles
            L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
            maxZoom: 19,
            attribution:
                '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>',
            }).addTo(map);

            // add popup to each feature
            function onEachFeature(feature, layer) {
                if (feature.properties && feature.properties.name) {
                    layer.bindPopup(feature.properties.name);
                }
            }

            // add the GeoJSON feature layer
            var geojsonLayer = L.geoJSON({{ points | tojson }}, { onEachFeature: onEachFeature }).addTo(
            map
            );

            // zoom map to GeoJSON feature layer
            map.fitBounds(geojsonLayer.getBounds());
        </script>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for point in points.features %}
                        <tr>
                            <th scope="row"><a href="{{ url_for('point.view', id=point.id) }}">{{ point.properties.name }}</a></th>
                            <td>
                                <a href="{{ url_for('point.edit', id=point.id) }}"><i class="bi bi-pencil-square"></i> Edit</a><br>
                                <a href="{{ url_for('point.delete', id=point.id) }}" class="link-danger"><i class="bi bi-trash"></i> Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <p class="lead">0 points</p>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/point/update_point.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url_for('point.list') }}">Points</a></li>
                <li class="breadcrumb-item"><a href="{{ url_for('point.view', id=point.id) }}">{{ point.properties.name }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">Edit</li>
            </ol>
        </nav>
        {{ super() }}
        <h1>{{title}}</h1>
        <hr>
        {% include '_point_form.html' %}
        <script type="application/javascript" nonce="{{ csp_nonce() }}">
            // initialize Leaflet
            var map = L.map("mapid");

            // add the OpenStreetMap tiles
            L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
            maxZoom: 19,
            attribution:
                '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>',
            }).addTo(map);

            // add popup to each feature
            function onEachFeature(feature, layer) {
                if (feature.properties && feature.properties.name) {
                    layer.bindPopup(feature.properties.name);
                }
            }

            // add the GeoJSON feature layer
            var geojsonLayer = L.geoJSON({{ point | tojson }}, { onEachFeature: onEachFeature }).addTo(map);

            // zoom map to GeoJSON feature layer
            map.fitBounds(geojsonLayer.getBounds());

            var marker = L.marker();

            function onMapClick(e) {
            marker
                .setLatLng(e.latlng)
                .addTo(map)
                .bindPopup(e.latlng.lat.toString() + "<br>" + e.latlng.lng.toString())
                .openPopup();
            document.getElementById('geometry').value=JSON.stringify(marker.toGeoJSON().geometry)
            }

            map.on("click", onMapClick);  
        </script>
    </div>
</div>
{% endblock %}

app/templates/point/view_point.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url_for('point.list') }}">Points</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ title }}</li>
            </ol>
        </nav>
        {{ super() }}
        <h1 class="text-truncate">{{ title }}</h1>
        <hr>
        {% include '_point_description.html' %}
        <div class="d-grid gap-3 d-sm-block">
            <a class="btn btn-primary" href="{{ url_for('point.edit', id=point.id) }}"><i class="bi bi-pencil-square"></i> Edit</a>
            <a class="btn btn-danger" href="{{ url_for('point.delete', id=point.id) }}"><i class="bi bi-trash"></i> Delete</a>
        </div>
    </div>
</div>
{% endblock %}